version: '3.3'
services:
  database:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: burritos
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./volumes/pgadmin/core:/var/lib/pgadmin
      - ./volumes/pgadmin/config/servers.json:/pgadmin4/servers.json
