name: CI/CD
on:
  push:
   branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-20.04
  
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: burritos
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'
    
      - name: Install dependencies
        run: npm install
      
      - name: Configure env file
        run: |
          echo DATABASE_URL="$API_DB_PORT" > .env
          echo API_KEY="acme123" >> .env
        env:
          API_DB_PORT: postgresql://root:root@localhost:${{ job.services.postgres.ports[5432] }}/burritos?schema=public

      - name: Build prisma
        run: npx prisma generate

      - name: Execute tsc
        run: npx tsc

      - name: Execute lint
        run: npm run lint

      - name: Execute migrations
        run: npx prisma migrate dev
  
      - name: Execute test
        run: npm run test:e2e
  CD:
    needs: [CI]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'
    
      - name: Install dependencies
        run: npm install
      
      - name: Configure env file
        run: |
          echo DATABASE_URL="$API_DB_PORT" > .env
        env:
          API_DB_PORT: ${{ secrets.DEPLOYED_DATABASE_URL }}

      - name: Run migrations
        run: npx prisma migrate dev

      - name: Compile code
        run: rm -f *.env && npm run build

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: burritos
          environment_name: Burritos-env
          version_label: prod-${{ github.head_ref }}.${{ github.sha }}
          region: us-east-2
          deployment_package: deploy.zip
          use_existing_version_if_available: true

